ORACLE_DSN   dbi:ODBC:Driver={ODBC Driver 18 for SQL Server};Server=<mssql-server-name>.database.windows.net;Database=sql2pg-demo2;TrustServerCertificate=yes
ORACLE_USER  <mssql-user>
ORACLE_PWD   <mssql-password>

# source schema, exact case
SCHEMA         SalesLT
EXPORT_SCHEMA  1
CREATE_SCHEMA  1
PG_SCHEMA      saleslt

PG_DSN     dbi:Pg:dbname=postgres;host=<servern-name>.postgres.database.azure.com;port=5432
PG_USER    <user>
PG_PWD     <password>
PG_VERSION 16

CLIENT_ENCODING	UTF8
DATA_LIMIT 10000
TRUNCATE_TABLE	0
DROP_ROWVERSION  1

CASE_INSENSITIVE_SEARCH	0
DATA_TYPE  VARCHAR:text,NVARCHAR:text,CHAR:text,NCHAR:text,TEXT:text,NTEXT:text,NAME:text,sysname:text,PHONE:text,ORDERNUMBER:text,ACCOUNTNUMBER:text,MONEY:numeric,SMALLMONEY:numeric,NAMESTYLE:smallint,FLAG:smallint

PG_INITIAL_COMMAND	SET session_replication_role = replica
